import type { CruxPortableBundle } from "@crux/formats";

export const createStarterBundle = (
  now = new Date().toISOString(),
): CruxPortableBundle => ({
  format: "crux-bundle/0.1",
  generated_at: now,
  organisations: [
    {
      schema_version: "0.1",
      id: "organisation:pilot",
      name: "Your organisation",
      description: "Describe the organisation publishing this AI transparency record.",
      disclosure: "public",
      external_refs: [],
      created_at: now,
    },
  ],
  ai_uses: [
    {
      schema_version: "0.1",
      id: "ai-use:primary",
      organisation_ref: "organisation:pilot",
      name: "A use of AI",
      purpose: "Describe why the organisation uses AI here and what it is trying to achieve.",
      public_summary: "A plain-language explanation of where AI is involved.",
      status: "active",
      people_affected: [],
      consequential: false,
      system_refs: ["system:primary"],
      disclosure: "public",
      external_refs: [],
      created_at: now,
    },
  ],
  systems: [
    {
      schema_version: "0.1",
      id: "system:primary",
      name: "AI-supported workflow",
      description: "Describe the system or workflow without starting with the model name.",
      ai_use_refs: ["ai-use:primary"],
      influence: ["assistive"],
      agency: "none",
      status: "active",
      current_version_ref: "system-version:primary:0.1",
      disclosure: "public",
      external_refs: [],
      created_at: now,
    },
  ],
  system_versions: [
    {
      schema_version: "0.1",
      id: "system-version:primary:0.1",
      system_ref: "system:primary",
      version: "0.1",
      effective_from: now,
      process: {
        id: "process:primary",
        name: "AI-supported workflow",
        description: "A simple starting process for the pilot. Add detail as you learn what matters.",
        nodes: [
          {
            id: "node:input",
            type: "input",
            name: "Information enters the process",
            disclosure: "public",
          },
          {
            id: "node:ai",
            type: "ai",
            name: "AI contributes",
            component_ref: "component:primary-model",
            purpose: "Describe what the AI does at this point.",
            disclosure: "public",
          },
          {
            id: "node:human",
            type: "human",
            name: "Human judgement",
            human_role_ref: "role:reviewer",
            disclosure: "public",
          },
          {
            id: "node:output",
            type: "output",
            name: "Outcome or output",
            disclosure: "public",
          },
        ],
        edges: [
          { from: "node:input", to: "node:ai", carries: [] },
          { from: "node:ai", to: "node:human", carries: [] },
          { from: "node:human", to: "node:output", carries: [] },
        ],
      },
      components: [
        {
          id: "component:primary-model",
          kind: "model",
          name: "AI model",
          purpose: "The model used in this part of the workflow.",
          model_identifier: { status: "unknown" },
          externally_provided: true,
          disclosure: "internal",
          external_refs: [],
        },
      ],
      data_sources: [],
      human_roles: [
        {
          id: "role:reviewer",
          name: "Human reviewer",
          responsibilities: ["Review the AI contribution and remain accountable for the outcome."],
          can_override_ai: true,
          disclosure: "public",
        },
      ],
      decisions: [],
      actions: [],
      risks: [],
      safeguards: [],
      disclosure: "public",
      external_refs: [],
      published_at: now,
    },
  ],
  claims: [
    {
      schema_version: "0.1",
      id: "claim:primary",
      type: "descriptive",
      statement: "AI supports this process, but this claim has not yet been evidenced.",
      applies_to: [
        { kind: "system_version", ref: "system-version:primary:0.1" },
      ],
      status: "active",
      disclosure: "public",
      created_at: now,
    },
  ],
  evidence: [],
  evidence_links: [],
  evaluation_definitions: [],
  evaluation_runs: [],
  evaluation_cases: [],
  runs: [],
  events: [],
  traces: [],
  receipts: [],
  observations: [],
});
